version: "3.0"
services:
  server:
    image: node:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node_app
    networks:
      - nginx_network
    ports:
      - 3000:3000
  core:
    image: nginx:latest
    restart: always
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: nginx_app
    depends_on:
      - server
    volumes:
      - ./core/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_network
    ports:
      - 80:80

networks:
  nginx_network:
    driver: bridge

